//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHangDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KhachHangDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SoTienNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        private int MaKhachHangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SoTienNo {
            get {
                return this.SoTienNoField;
            }
            set {
                if ((this.SoTienNoField.Equals(value) != true)) {
                    this.SoTienNoField = value;
                    this.RaisePropertyChanged("SoTienNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MaKhachHang {
            get {
                return this.MaKhachHangField;
            }
            set {
                if ((this.MaKhachHangField.Equals(value) != true)) {
                    this.MaKhachHangField = value;
                    this.RaisePropertyChanged("MaKhachHang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsKhachHangDAL.wsKhachHangSoap")]
    public interface wsKhachHangSoap {
        
        // CODEGEN: Generating message contract since element name getListKhachHangResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListKhachHang", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangResponse getListKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangRequest request);
        
        // CODEGEN: Generating message contract since element name khachhangDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertKhachHang", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangResponse insertKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangRequest request);
        
        // CODEGEN: Generating message contract since element name khachhangDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addNewKhachHang", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangResponse addNewKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangRequest request);
        
        // CODEGEN: Generating message contract since element name kh from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteKhachHang", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangResponse deleteKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangRequest request);
        
        // CODEGEN: Generating message contract since element name kh from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateKhachHang", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangResponse updateKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangRequest request);
        
        // CODEGEN: Generating message contract since element name hoten from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaKhachHang", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangResponse getMaKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangRequest request);
        
        // CODEGEN: Generating message contract since element name getKhachHangInfoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getKhachHangInfo", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoResponse getKhachHangInfo(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListKhachHangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListKhachHang", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangRequestBody Body;
        
        public getListKhachHangRequest() {
        }
        
        public getListKhachHangRequest(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListKhachHangRequestBody {
        
        public getListKhachHangRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListKhachHangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListKhachHangResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangResponseBody Body;
        
        public getListKhachHangResponse() {
        }
        
        public getListKhachHangResponse(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListKhachHangResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO[] getListKhachHangResult;
        
        public getListKhachHangResponseBody() {
        }
        
        public getListKhachHangResponseBody(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO[] getListKhachHangResult) {
            this.getListKhachHangResult = getListKhachHangResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertKhachHangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertKhachHang", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangRequestBody Body;
        
        public insertKhachHangRequest() {
        }
        
        public insertKhachHangRequest(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertKhachHangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO khachhangDTO;
        
        public insertKhachHangRequestBody() {
        }
        
        public insertKhachHangRequestBody(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO khachhangDTO) {
            this.khachhangDTO = khachhangDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertKhachHangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertKhachHangResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangResponseBody Body;
        
        public insertKhachHangResponse() {
        }
        
        public insertKhachHangResponse(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertKhachHangResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertKhachHangResult;
        
        public insertKhachHangResponseBody() {
        }
        
        public insertKhachHangResponseBody(bool insertKhachHangResult) {
            this.insertKhachHangResult = insertKhachHangResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNewKhachHangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNewKhachHang", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangRequestBody Body;
        
        public addNewKhachHangRequest() {
        }
        
        public addNewKhachHangRequest(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addNewKhachHangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO khachhangDTO;
        
        public addNewKhachHangRequestBody() {
        }
        
        public addNewKhachHangRequestBody(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO khachhangDTO) {
            this.khachhangDTO = khachhangDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNewKhachHangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNewKhachHangResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangResponseBody Body;
        
        public addNewKhachHangResponse() {
        }
        
        public addNewKhachHangResponse(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addNewKhachHangResponseBody {
        
        public addNewKhachHangResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteKhachHangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteKhachHang", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangRequestBody Body;
        
        public deleteKhachHangRequest() {
        }
        
        public deleteKhachHangRequest(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteKhachHangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO kh;
        
        public deleteKhachHangRequestBody() {
        }
        
        public deleteKhachHangRequestBody(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO kh) {
            this.kh = kh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteKhachHangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteKhachHangResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangResponseBody Body;
        
        public deleteKhachHangResponse() {
        }
        
        public deleteKhachHangResponse(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteKhachHangResponseBody {
        
        public deleteKhachHangResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateKhachHangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateKhachHang", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangRequestBody Body;
        
        public updateKhachHangRequest() {
        }
        
        public updateKhachHangRequest(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateKhachHangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO kh;
        
        public updateKhachHangRequestBody() {
        }
        
        public updateKhachHangRequestBody(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO kh) {
            this.kh = kh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateKhachHangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateKhachHangResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangResponseBody Body;
        
        public updateKhachHangResponse() {
        }
        
        public updateKhachHangResponse(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateKhachHangResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool updateKhachHangResult;
        
        public updateKhachHangResponseBody() {
        }
        
        public updateKhachHangResponseBody(bool updateKhachHangResult) {
            this.updateKhachHangResult = updateKhachHangResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaKhachHangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaKhachHang", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangRequestBody Body;
        
        public getMaKhachHangRequest() {
        }
        
        public getMaKhachHangRequest(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMaKhachHangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hoten;
        
        public getMaKhachHangRequestBody() {
        }
        
        public getMaKhachHangRequestBody(string hoten) {
            this.hoten = hoten;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaKhachHangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaKhachHangResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangResponseBody Body;
        
        public getMaKhachHangResponse() {
        }
        
        public getMaKhachHangResponse(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMaKhachHangResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getMaKhachHangResult;
        
        public getMaKhachHangResponseBody() {
        }
        
        public getMaKhachHangResponseBody(int getMaKhachHangResult) {
            this.getMaKhachHangResult = getMaKhachHangResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKhachHangInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKhachHangInfo", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoRequestBody Body;
        
        public getKhachHangInfoRequest() {
        }
        
        public getKhachHangInfoRequest(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getKhachHangInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int makhachhang;
        
        public getKhachHangInfoRequestBody() {
        }
        
        public getKhachHangInfoRequestBody(int makhachhang) {
            this.makhachhang = makhachhang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKhachHangInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKhachHangInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoResponseBody Body;
        
        public getKhachHangInfoResponse() {
        }
        
        public getKhachHangInfoResponse(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getKhachHangInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO getKhachHangInfoResult;
        
        public getKhachHangInfoResponseBody() {
        }
        
        public getKhachHangInfoResponseBody(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO getKhachHangInfoResult) {
            this.getKhachHangInfoResult = getKhachHangInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsKhachHangSoapChannel : DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsKhachHangSoapClient : System.ServiceModel.ClientBase<DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap>, DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap {
        
        public wsKhachHangSoapClient() {
        }
        
        public wsKhachHangSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsKhachHangSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsKhachHangSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsKhachHangSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangResponse DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap.getListKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangRequest request) {
            return base.Channel.getListKhachHang(request);
        }
        
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO[] getListKhachHang() {
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangRequestBody();
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getListKhachHangResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap)(this)).getListKhachHang(inValue);
            return retVal.Body.getListKhachHangResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangResponse DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap.insertKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangRequest request) {
            return base.Channel.insertKhachHang(request);
        }
        
        public bool insertKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO khachhangDTO) {
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangRequestBody();
            inValue.Body.khachhangDTO = khachhangDTO;
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.insertKhachHangResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap)(this)).insertKhachHang(inValue);
            return retVal.Body.insertKhachHangResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangResponse DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap.addNewKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangRequest request) {
            return base.Channel.addNewKhachHang(request);
        }
        
        public void addNewKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO khachhangDTO) {
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangRequestBody();
            inValue.Body.khachhangDTO = khachhangDTO;
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.addNewKhachHangResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap)(this)).addNewKhachHang(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangResponse DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap.deleteKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangRequest request) {
            return base.Channel.deleteKhachHang(request);
        }
        
        public void deleteKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO kh) {
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangRequestBody();
            inValue.Body.kh = kh;
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.deleteKhachHangResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap)(this)).deleteKhachHang(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangResponse DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap.updateKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangRequest request) {
            return base.Channel.updateKhachHang(request);
        }
        
        public bool updateKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO kh) {
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangRequestBody();
            inValue.Body.kh = kh;
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.updateKhachHangResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap)(this)).updateKhachHang(inValue);
            return retVal.Body.updateKhachHangResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangResponse DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap.getMaKhachHang(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangRequest request) {
            return base.Channel.getMaKhachHang(request);
        }
        
        public int getMaKhachHang(string hoten) {
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangRequestBody();
            inValue.Body.hoten = hoten;
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getMaKhachHangResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap)(this)).getMaKhachHang(inValue);
            return retVal.Body.getMaKhachHangResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoResponse DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap.getKhachHangInfo(DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoRequest request) {
            return base.Channel.getKhachHangInfo(request);
        }
        
        public DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.KhachHangDTO getKhachHangInfo(int makhachhang) {
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoRequestBody();
            inValue.Body.makhachhang = makhachhang;
            DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.getKhachHangInfoResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsKhachHangDAL.wsKhachHangSoap)(this)).getKhachHangInfo(inValue);
            return retVal.Body.getKhachHangInfoResult;
        }
    }
}
