//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyNhaSach_Official.wsThamSoBLL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsThamSoBLL.wsThamSoBLLSoap")]
    public interface wsThamSoBLLSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSoLuongNhapMin", ReplyAction="*")]
        int getSoLuongNhapMin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSoLuongTonMax", ReplyAction="*")]
        int getSoLuongTonMax();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSoTienKhachHangNoMax", ReplyAction="*")]
        int getSoTienKhachHangNoMax();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSoLuongTonSauBanMin", ReplyAction="*")]
        int getSoLuongTonSauBanMin();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsThamSoBLLSoapChannel : DoAn_QuanLyNhaSach_Official.wsThamSoBLL.wsThamSoBLLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsThamSoBLLSoapClient : System.ServiceModel.ClientBase<DoAn_QuanLyNhaSach_Official.wsThamSoBLL.wsThamSoBLLSoap>, DoAn_QuanLyNhaSach_Official.wsThamSoBLL.wsThamSoBLLSoap {
        
        public wsThamSoBLLSoapClient() {
        }
        
        public wsThamSoBLLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsThamSoBLLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsThamSoBLLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsThamSoBLLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getSoLuongNhapMin() {
            return base.Channel.getSoLuongNhapMin();
        }
        
        public int getSoLuongTonMax() {
            return base.Channel.getSoLuongTonMax();
        }
        
        public int getSoTienKhachHangNoMax() {
            return base.Channel.getSoTienKhachHangNoMax();
        }
        
        public int getSoLuongTonSauBanMin() {
            return base.Channel.getSoLuongTonSauBanMin();
        }
    }
}
