//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaoCaoNoCongDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BaoCaoNoCongDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.ExtensionDataObject ExtensionData1Field;
        
        private int NoCuoiField;
        
        private int PhatSinhField;
        
        private int NoDauField;
        
        private int MaKhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThangField;
        
        private int MaBaoCaoNoCongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NoCuoi {
            get {
                return this.NoCuoiField;
            }
            set {
                if ((this.NoCuoiField.Equals(value) != true)) {
                    this.NoCuoiField = value;
                    this.RaisePropertyChanged("NoCuoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PhatSinh {
            get {
                return this.PhatSinhField;
            }
            set {
                if ((this.PhatSinhField.Equals(value) != true)) {
                    this.PhatSinhField = value;
                    this.RaisePropertyChanged("PhatSinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NoDau {
            get {
                return this.NoDauField;
            }
            set {
                if ((this.NoDauField.Equals(value) != true)) {
                    this.NoDauField = value;
                    this.RaisePropertyChanged("NoDau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int MaKhachHang {
            get {
                return this.MaKhachHangField;
            }
            set {
                if ((this.MaKhachHangField.Equals(value) != true)) {
                    this.MaKhachHangField = value;
                    this.RaisePropertyChanged("MaKhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Thang {
            get {
                return this.ThangField;
            }
            set {
                if ((object.ReferenceEquals(this.ThangField, value) != true)) {
                    this.ThangField = value;
                    this.RaisePropertyChanged("Thang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int MaBaoCaoNoCong {
            get {
                return this.MaBaoCaoNoCongField;
            }
            set {
                if ((this.MaBaoCaoNoCongField.Equals(value) != true)) {
                    this.MaBaoCaoNoCongField = value;
                    this.RaisePropertyChanged("MaBaoCaoNoCong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap")]
    public interface wsBaoCaoNoCongBLLSoap {
        
        // CODEGEN: Generating message contract since element name getListBaoCaoNoCongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListBaoCaoNoCong", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongResponse getListBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongRequest request);
        
        // CODEGEN: Generating message contract since element name baocaoDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertBaoCaoNoCong", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongResponse insertBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongRequest request);
        
        // CODEGEN: Generating message contract since element name baocaoDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBaoCaoNoCong", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongResponse updateBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongRequest request);
        
        // CODEGEN: Generating message contract since element name baocaoDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteBaoCaoNoCong", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongResponse deleteBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListBaoCaoNoCongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListBaoCaoNoCong", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongRequestBody Body;
        
        public getListBaoCaoNoCongRequest() {
        }
        
        public getListBaoCaoNoCongRequest(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListBaoCaoNoCongRequestBody {
        
        public getListBaoCaoNoCongRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListBaoCaoNoCongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListBaoCaoNoCongResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongResponseBody Body;
        
        public getListBaoCaoNoCongResponse() {
        }
        
        public getListBaoCaoNoCongResponse(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListBaoCaoNoCongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO[] getListBaoCaoNoCongResult;
        
        public getListBaoCaoNoCongResponseBody() {
        }
        
        public getListBaoCaoNoCongResponseBody(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO[] getListBaoCaoNoCongResult) {
            this.getListBaoCaoNoCongResult = getListBaoCaoNoCongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertBaoCaoNoCongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertBaoCaoNoCong", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongRequestBody Body;
        
        public insertBaoCaoNoCongRequest() {
        }
        
        public insertBaoCaoNoCongRequest(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertBaoCaoNoCongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO;
        
        public insertBaoCaoNoCongRequestBody() {
        }
        
        public insertBaoCaoNoCongRequestBody(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO) {
            this.baocaoDTO = baocaoDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertBaoCaoNoCongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertBaoCaoNoCongResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongResponseBody Body;
        
        public insertBaoCaoNoCongResponse() {
        }
        
        public insertBaoCaoNoCongResponse(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertBaoCaoNoCongResponseBody {
        
        public insertBaoCaoNoCongResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBaoCaoNoCongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBaoCaoNoCong", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongRequestBody Body;
        
        public updateBaoCaoNoCongRequest() {
        }
        
        public updateBaoCaoNoCongRequest(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateBaoCaoNoCongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO;
        
        public updateBaoCaoNoCongRequestBody() {
        }
        
        public updateBaoCaoNoCongRequestBody(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO) {
            this.baocaoDTO = baocaoDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBaoCaoNoCongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBaoCaoNoCongResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongResponseBody Body;
        
        public updateBaoCaoNoCongResponse() {
        }
        
        public updateBaoCaoNoCongResponse(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateBaoCaoNoCongResponseBody {
        
        public updateBaoCaoNoCongResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteBaoCaoNoCongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteBaoCaoNoCong", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongRequestBody Body;
        
        public deleteBaoCaoNoCongRequest() {
        }
        
        public deleteBaoCaoNoCongRequest(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteBaoCaoNoCongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO;
        
        public deleteBaoCaoNoCongRequestBody() {
        }
        
        public deleteBaoCaoNoCongRequestBody(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO) {
            this.baocaoDTO = baocaoDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteBaoCaoNoCongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteBaoCaoNoCongResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongResponseBody Body;
        
        public deleteBaoCaoNoCongResponse() {
        }
        
        public deleteBaoCaoNoCongResponse(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteBaoCaoNoCongResponseBody {
        
        public deleteBaoCaoNoCongResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsBaoCaoNoCongBLLSoapChannel : DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsBaoCaoNoCongBLLSoapClient : System.ServiceModel.ClientBase<DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap>, DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap {
        
        public wsBaoCaoNoCongBLLSoapClient() {
        }
        
        public wsBaoCaoNoCongBLLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsBaoCaoNoCongBLLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBaoCaoNoCongBLLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBaoCaoNoCongBLLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongResponse DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap.getListBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongRequest request) {
            return base.Channel.getListBaoCaoNoCong(request);
        }
        
        public DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO[] getListBaoCaoNoCong() {
            DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongRequest inValue = new DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongRequestBody();
            DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.getListBaoCaoNoCongResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap)(this)).getListBaoCaoNoCong(inValue);
            return retVal.Body.getListBaoCaoNoCongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongResponse DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap.insertBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongRequest request) {
            return base.Channel.insertBaoCaoNoCong(request);
        }
        
        public void insertBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO) {
            DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongRequest inValue = new DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongRequestBody();
            inValue.Body.baocaoDTO = baocaoDTO;
            DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.insertBaoCaoNoCongResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap)(this)).insertBaoCaoNoCong(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongResponse DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap.updateBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongRequest request) {
            return base.Channel.updateBaoCaoNoCong(request);
        }
        
        public void updateBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO) {
            DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongRequest inValue = new DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongRequestBody();
            inValue.Body.baocaoDTO = baocaoDTO;
            DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.updateBaoCaoNoCongResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap)(this)).updateBaoCaoNoCong(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongResponse DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap.deleteBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongRequest request) {
            return base.Channel.deleteBaoCaoNoCong(request);
        }
        
        public void deleteBaoCaoNoCong(DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.BaoCaoNoCongDTO baocaoDTO) {
            DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongRequest inValue = new DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongRequestBody();
            inValue.Body.baocaoDTO = baocaoDTO;
            DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.deleteBaoCaoNoCongResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsBaoCaoNoCongBLL.wsBaoCaoNoCongBLLSoap)(this)).deleteBaoCaoNoCong(inValue);
        }
    }
}
