//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiTietPhieuNhapSachDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChiTietPhieuNhapSachDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ExtensionDataObject ExtensionData1Field;
        
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSachField;
        
        private int MaChiTietPhieuNhapSachField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MaSach {
            get {
                return this.MaSachField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSachField, value) != true)) {
                    this.MaSachField = value;
                    this.RaisePropertyChanged("MaSach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MaChiTietPhieuNhapSach {
            get {
                return this.MaChiTietPhieuNhapSachField;
            }
            set {
                if ((this.MaChiTietPhieuNhapSachField.Equals(value) != true)) {
                    this.MaChiTietPhieuNhapSachField = value;
                    this.RaisePropertyChanged("MaChiTietPhieuNhapSach");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap")]
    public interface wsChiTietPhieuNhapSachBLLSoap {
        
        // CODEGEN: Generating message contract since element name chitiet from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertChiTietPhieuNhapSach", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachResponse insertChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachRequest request);
        
        // CODEGEN: Generating message contract since element name masach from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSoLuongSachNhap", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapResponse getSoLuongSachNhap(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapRequest request);
        
        // CODEGEN: Generating message contract since element name getListChiTietPhieuNhapSachResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListChiTietPhieuNhapSach", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachResponse getListChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachRequest request);
        
        // CODEGEN: Generating message contract since element name chitiet from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteChiTietPhieuNhapSach", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachResponse deleteChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachRequest request);
        
        // CODEGEN: Generating message contract since element name chitiet from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateChiTietPhieuNhapSach", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachResponse updateChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachRequest request);
        
        // CODEGEN: Generating message contract since element name masach from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaChiTietPhieuNhapSach", ReplyAction="*")]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachResponse getMaChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertChiTietPhieuNhapSachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertChiTietPhieuNhapSach", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachRequestBody Body;
        
        public insertChiTietPhieuNhapSachRequest() {
        }
        
        public insertChiTietPhieuNhapSachRequest(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertChiTietPhieuNhapSachRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet;
        
        public insertChiTietPhieuNhapSachRequestBody() {
        }
        
        public insertChiTietPhieuNhapSachRequestBody(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet) {
            this.chitiet = chitiet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertChiTietPhieuNhapSachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertChiTietPhieuNhapSachResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachResponseBody Body;
        
        public insertChiTietPhieuNhapSachResponse() {
        }
        
        public insertChiTietPhieuNhapSachResponse(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertChiTietPhieuNhapSachResponseBody {
        
        public insertChiTietPhieuNhapSachResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSoLuongSachNhapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSoLuongSachNhap", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapRequestBody Body;
        
        public getSoLuongSachNhapRequest() {
        }
        
        public getSoLuongSachNhapRequest(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getSoLuongSachNhapRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string masach;
        
        public getSoLuongSachNhapRequestBody() {
        }
        
        public getSoLuongSachNhapRequestBody(string masach) {
            this.masach = masach;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSoLuongSachNhapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSoLuongSachNhapResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapResponseBody Body;
        
        public getSoLuongSachNhapResponse() {
        }
        
        public getSoLuongSachNhapResponse(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getSoLuongSachNhapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getSoLuongSachNhapResult;
        
        public getSoLuongSachNhapResponseBody() {
        }
        
        public getSoLuongSachNhapResponseBody(int getSoLuongSachNhapResult) {
            this.getSoLuongSachNhapResult = getSoLuongSachNhapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListChiTietPhieuNhapSachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListChiTietPhieuNhapSach", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachRequestBody Body;
        
        public getListChiTietPhieuNhapSachRequest() {
        }
        
        public getListChiTietPhieuNhapSachRequest(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListChiTietPhieuNhapSachRequestBody {
        
        public getListChiTietPhieuNhapSachRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListChiTietPhieuNhapSachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListChiTietPhieuNhapSachResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachResponseBody Body;
        
        public getListChiTietPhieuNhapSachResponse() {
        }
        
        public getListChiTietPhieuNhapSachResponse(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListChiTietPhieuNhapSachResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO[] getListChiTietPhieuNhapSachResult;
        
        public getListChiTietPhieuNhapSachResponseBody() {
        }
        
        public getListChiTietPhieuNhapSachResponseBody(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO[] getListChiTietPhieuNhapSachResult) {
            this.getListChiTietPhieuNhapSachResult = getListChiTietPhieuNhapSachResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteChiTietPhieuNhapSachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteChiTietPhieuNhapSach", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachRequestBody Body;
        
        public deleteChiTietPhieuNhapSachRequest() {
        }
        
        public deleteChiTietPhieuNhapSachRequest(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteChiTietPhieuNhapSachRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet;
        
        public deleteChiTietPhieuNhapSachRequestBody() {
        }
        
        public deleteChiTietPhieuNhapSachRequestBody(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet) {
            this.chitiet = chitiet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteChiTietPhieuNhapSachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteChiTietPhieuNhapSachResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachResponseBody Body;
        
        public deleteChiTietPhieuNhapSachResponse() {
        }
        
        public deleteChiTietPhieuNhapSachResponse(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteChiTietPhieuNhapSachResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool deleteChiTietPhieuNhapSachResult;
        
        public deleteChiTietPhieuNhapSachResponseBody() {
        }
        
        public deleteChiTietPhieuNhapSachResponseBody(bool deleteChiTietPhieuNhapSachResult) {
            this.deleteChiTietPhieuNhapSachResult = deleteChiTietPhieuNhapSachResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateChiTietPhieuNhapSachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateChiTietPhieuNhapSach", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachRequestBody Body;
        
        public updateChiTietPhieuNhapSachRequest() {
        }
        
        public updateChiTietPhieuNhapSachRequest(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateChiTietPhieuNhapSachRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet;
        
        public updateChiTietPhieuNhapSachRequestBody() {
        }
        
        public updateChiTietPhieuNhapSachRequestBody(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet) {
            this.chitiet = chitiet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateChiTietPhieuNhapSachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateChiTietPhieuNhapSachResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachResponseBody Body;
        
        public updateChiTietPhieuNhapSachResponse() {
        }
        
        public updateChiTietPhieuNhapSachResponse(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateChiTietPhieuNhapSachResponseBody {
        
        public updateChiTietPhieuNhapSachResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaChiTietPhieuNhapSachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaChiTietPhieuNhapSach", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachRequestBody Body;
        
        public getMaChiTietPhieuNhapSachRequest() {
        }
        
        public getMaChiTietPhieuNhapSachRequest(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMaChiTietPhieuNhapSachRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string masach;
        
        public getMaChiTietPhieuNhapSachRequestBody() {
        }
        
        public getMaChiTietPhieuNhapSachRequestBody(string masach) {
            this.masach = masach;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaChiTietPhieuNhapSachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaChiTietPhieuNhapSachResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachResponseBody Body;
        
        public getMaChiTietPhieuNhapSachResponse() {
        }
        
        public getMaChiTietPhieuNhapSachResponse(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMaChiTietPhieuNhapSachResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getMaChiTietPhieuNhapSachResult;
        
        public getMaChiTietPhieuNhapSachResponseBody() {
        }
        
        public getMaChiTietPhieuNhapSachResponseBody(int getMaChiTietPhieuNhapSachResult) {
            this.getMaChiTietPhieuNhapSachResult = getMaChiTietPhieuNhapSachResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsChiTietPhieuNhapSachBLLSoapChannel : DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsChiTietPhieuNhapSachBLLSoapClient : System.ServiceModel.ClientBase<DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap>, DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap {
        
        public wsChiTietPhieuNhapSachBLLSoapClient() {
        }
        
        public wsChiTietPhieuNhapSachBLLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsChiTietPhieuNhapSachBLLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsChiTietPhieuNhapSachBLLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsChiTietPhieuNhapSachBLLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachResponse DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap.insertChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachRequest request) {
            return base.Channel.insertChiTietPhieuNhapSach(request);
        }
        
        public void insertChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet) {
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachRequest inValue = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachRequestBody();
            inValue.Body.chitiet = chitiet;
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.insertChiTietPhieuNhapSachResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap)(this)).insertChiTietPhieuNhapSach(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapResponse DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap.getSoLuongSachNhap(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapRequest request) {
            return base.Channel.getSoLuongSachNhap(request);
        }
        
        public int getSoLuongSachNhap(string masach) {
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapRequest inValue = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapRequestBody();
            inValue.Body.masach = masach;
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getSoLuongSachNhapResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap)(this)).getSoLuongSachNhap(inValue);
            return retVal.Body.getSoLuongSachNhapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachResponse DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap.getListChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachRequest request) {
            return base.Channel.getListChiTietPhieuNhapSach(request);
        }
        
        public DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO[] getListChiTietPhieuNhapSach() {
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachRequest inValue = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachRequestBody();
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getListChiTietPhieuNhapSachResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap)(this)).getListChiTietPhieuNhapSach(inValue);
            return retVal.Body.getListChiTietPhieuNhapSachResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachResponse DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap.deleteChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachRequest request) {
            return base.Channel.deleteChiTietPhieuNhapSach(request);
        }
        
        public bool deleteChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet) {
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachRequest inValue = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachRequestBody();
            inValue.Body.chitiet = chitiet;
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.deleteChiTietPhieuNhapSachResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap)(this)).deleteChiTietPhieuNhapSach(inValue);
            return retVal.Body.deleteChiTietPhieuNhapSachResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachResponse DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap.updateChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachRequest request) {
            return base.Channel.updateChiTietPhieuNhapSach(request);
        }
        
        public void updateChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.ChiTietPhieuNhapSachDTO chitiet) {
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachRequest inValue = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachRequestBody();
            inValue.Body.chitiet = chitiet;
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.updateChiTietPhieuNhapSachResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap)(this)).updateChiTietPhieuNhapSach(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachResponse DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap.getMaChiTietPhieuNhapSach(DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachRequest request) {
            return base.Channel.getMaChiTietPhieuNhapSach(request);
        }
        
        public int getMaChiTietPhieuNhapSach(string masach) {
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachRequest inValue = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachRequestBody();
            inValue.Body.masach = masach;
            DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.getMaChiTietPhieuNhapSachResponse retVal = ((DoAn_QuanLyNhaSach_Official.wsChiTietPhieuNhapSachBLL.wsChiTietPhieuNhapSachBLLSoap)(this)).getMaChiTietPhieuNhapSach(inValue);
            return retVal.Body.getMaChiTietPhieuNhapSachResult;
        }
    }
}
