//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiTietHoaDonDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChiTietHoaDonDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DonGiaField;
        
        private int SoLuongBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSachField;
        
        private int MaChiTietHoaDonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SoLuongBan {
            get {
                return this.SoLuongBanField;
            }
            set {
                if ((this.SoLuongBanField.Equals(value) != true)) {
                    this.SoLuongBanField = value;
                    this.RaisePropertyChanged("SoLuongBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MaSach {
            get {
                return this.MaSachField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSachField, value) != true)) {
                    this.MaSachField = value;
                    this.RaisePropertyChanged("MaSach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MaChiTietHoaDon {
            get {
                return this.MaChiTietHoaDonField;
            }
            set {
                if ((this.MaChiTietHoaDonField.Equals(value) != true)) {
                    this.MaChiTietHoaDonField = value;
                    this.RaisePropertyChanged("MaChiTietHoaDon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsChiTietHoaDonDAL.wsChiTietHoaDonSoap")]
    public interface wsChiTietHoaDonSoap {
        
        // CODEGEN: Generating message contract since element name getListChiTietHoaDonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListChiTietHoaDon", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonResponse getListChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonRequest request);
        
        // CODEGEN: Generating message contract since element name chitietDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertChiTietHoaDon", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonResponse insertChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonRequest request);
        
        // CODEGEN: Generating message contract since element name masach from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaChiTietHoaDon", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonResponse getMaChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonRequest request);
        
        // CODEGEN: Generating message contract since element name deleteAllTableChiTietHoaDonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAllTableChiTietHoaDon", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonResponse deleteAllTableChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonRequest request);
        
        // CODEGEN: Generating message contract since element name masach from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTongTien", ReplyAction="*")]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienResponse getTongTien(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListChiTietHoaDonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListChiTietHoaDon", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonRequestBody Body;
        
        public getListChiTietHoaDonRequest() {
        }
        
        public getListChiTietHoaDonRequest(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListChiTietHoaDonRequestBody {
        
        public getListChiTietHoaDonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListChiTietHoaDonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListChiTietHoaDonResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonResponseBody Body;
        
        public getListChiTietHoaDonResponse() {
        }
        
        public getListChiTietHoaDonResponse(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListChiTietHoaDonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO[] getListChiTietHoaDonResult;
        
        public getListChiTietHoaDonResponseBody() {
        }
        
        public getListChiTietHoaDonResponseBody(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO[] getListChiTietHoaDonResult) {
            this.getListChiTietHoaDonResult = getListChiTietHoaDonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertChiTietHoaDonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertChiTietHoaDon", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonRequestBody Body;
        
        public insertChiTietHoaDonRequest() {
        }
        
        public insertChiTietHoaDonRequest(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertChiTietHoaDonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO chitietDTO;
        
        public insertChiTietHoaDonRequestBody() {
        }
        
        public insertChiTietHoaDonRequestBody(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO chitietDTO) {
            this.chitietDTO = chitietDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertChiTietHoaDonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertChiTietHoaDonResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonResponseBody Body;
        
        public insertChiTietHoaDonResponse() {
        }
        
        public insertChiTietHoaDonResponse(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertChiTietHoaDonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertChiTietHoaDonResult;
        
        public insertChiTietHoaDonResponseBody() {
        }
        
        public insertChiTietHoaDonResponseBody(bool insertChiTietHoaDonResult) {
            this.insertChiTietHoaDonResult = insertChiTietHoaDonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaChiTietHoaDonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaChiTietHoaDon", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonRequestBody Body;
        
        public getMaChiTietHoaDonRequest() {
        }
        
        public getMaChiTietHoaDonRequest(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMaChiTietHoaDonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string masach;
        
        public getMaChiTietHoaDonRequestBody() {
        }
        
        public getMaChiTietHoaDonRequestBody(string masach) {
            this.masach = masach;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaChiTietHoaDonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaChiTietHoaDonResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonResponseBody Body;
        
        public getMaChiTietHoaDonResponse() {
        }
        
        public getMaChiTietHoaDonResponse(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMaChiTietHoaDonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getMaChiTietHoaDonResult;
        
        public getMaChiTietHoaDonResponseBody() {
        }
        
        public getMaChiTietHoaDonResponseBody(int getMaChiTietHoaDonResult) {
            this.getMaChiTietHoaDonResult = getMaChiTietHoaDonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteAllTableChiTietHoaDonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteAllTableChiTietHoaDon", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonRequestBody Body;
        
        public deleteAllTableChiTietHoaDonRequest() {
        }
        
        public deleteAllTableChiTietHoaDonRequest(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteAllTableChiTietHoaDonRequestBody {
        
        public deleteAllTableChiTietHoaDonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteAllTableChiTietHoaDonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteAllTableChiTietHoaDonResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonResponseBody Body;
        
        public deleteAllTableChiTietHoaDonResponse() {
        }
        
        public deleteAllTableChiTietHoaDonResponse(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteAllTableChiTietHoaDonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO[] deleteAllTableChiTietHoaDonResult;
        
        public deleteAllTableChiTietHoaDonResponseBody() {
        }
        
        public deleteAllTableChiTietHoaDonResponseBody(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO[] deleteAllTableChiTietHoaDonResult) {
            this.deleteAllTableChiTietHoaDonResult = deleteAllTableChiTietHoaDonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTongTienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTongTien", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienRequestBody Body;
        
        public getTongTienRequest() {
        }
        
        public getTongTienRequest(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTongTienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string masach;
        
        public getTongTienRequestBody() {
        }
        
        public getTongTienRequestBody(string masach) {
            this.masach = masach;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTongTienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTongTienResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienResponseBody Body;
        
        public getTongTienResponse() {
        }
        
        public getTongTienResponse(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTongTienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getTongTienResult;
        
        public getTongTienResponseBody() {
        }
        
        public getTongTienResponseBody(int getTongTienResult) {
            this.getTongTienResult = getTongTienResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsChiTietHoaDonSoapChannel : DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsChiTietHoaDonSoapClient : System.ServiceModel.ClientBase<DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap>, DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap {
        
        public wsChiTietHoaDonSoapClient() {
        }
        
        public wsChiTietHoaDonSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsChiTietHoaDonSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsChiTietHoaDonSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsChiTietHoaDonSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonResponse DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap.getListChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonRequest request) {
            return base.Channel.getListChiTietHoaDon(request);
        }
        
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO[] getListChiTietHoaDon() {
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonRequestBody();
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getListChiTietHoaDonResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap)(this)).getListChiTietHoaDon(inValue);
            return retVal.Body.getListChiTietHoaDonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonResponse DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap.insertChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonRequest request) {
            return base.Channel.insertChiTietHoaDon(request);
        }
        
        public bool insertChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO chitietDTO) {
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonRequestBody();
            inValue.Body.chitietDTO = chitietDTO;
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.insertChiTietHoaDonResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap)(this)).insertChiTietHoaDon(inValue);
            return retVal.Body.insertChiTietHoaDonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonResponse DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap.getMaChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonRequest request) {
            return base.Channel.getMaChiTietHoaDon(request);
        }
        
        public int getMaChiTietHoaDon(string masach) {
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonRequestBody();
            inValue.Body.masach = masach;
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getMaChiTietHoaDonResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap)(this)).getMaChiTietHoaDon(inValue);
            return retVal.Body.getMaChiTietHoaDonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonResponse DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap.deleteAllTableChiTietHoaDon(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonRequest request) {
            return base.Channel.deleteAllTableChiTietHoaDon(request);
        }
        
        public DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.ChiTietHoaDonDTO[] deleteAllTableChiTietHoaDon() {
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonRequestBody();
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.deleteAllTableChiTietHoaDonResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap)(this)).deleteAllTableChiTietHoaDon(inValue);
            return retVal.Body.deleteAllTableChiTietHoaDonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienResponse DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap.getTongTien(DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienRequest request) {
            return base.Channel.getTongTien(request);
        }
        
        public int getTongTien(string masach) {
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienRequest inValue = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienRequest();
            inValue.Body = new DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienRequestBody();
            inValue.Body.masach = masach;
            DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.getTongTienResponse retVal = ((DoAn_QuanLyNhaSach_WS_BLL.wsChiTietHoaDonDAL.wsChiTietHoaDonSoap)(this)).getTongTien(inValue);
            return retVal.Body.getTongTienResult;
        }
    }
}
